package edu.brown.cs.student.server;

import com.squareup.moshi.Moshi;
import com.squareup.moshi.Types;
import edu.brown.cs.student.server.handlers.DefaultHandler;
import edu.brown.cs.student.server.handlers.SportsHandler;
import edu.brown.cs.student.util.Scorer;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.Buffer;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import spark.Spark;

public class APITest {
  private static final Moshi moshi = new Moshi.Builder().build();
  private static final Scorer s = new Scorer();

  @BeforeAll
  public static void setup_before_everything() {
    // Setting port 0 will cause Spark to use an arbitrary available port.
    Spark.port(0);
    Logger.getLogger("").setLevel(Level.WARNING); // empty name = root logger
  }

  /**
   * Shared state for all tests. We clear this state out after every test runs.
   */
  @BeforeEach
  public void setup() {
    Spark.get("sports", new SportsHandler(moshi, s));
    Spark.get("*", new DefaultHandler());
    Spark.init();
    Spark.awaitInitialization(); // don't continue until the server is listening
  }

  @AfterEach
  public void teardown() {
    // Gracefully stop Spark listening on all endpoints
    Spark.unmap("/sports");

    Spark.awaitStop(); // don't proceed until the server is stopped
  }

  /**
   * Helper to start a connection to a specific API endpoint/params
   * @param apiCall the call string, including endpoint
   *                (NOTE: this would be better if it had more structure!)
   * @return the connection for the given URL, just after connecting
   * @throws IOException if the connection fails for some reason
   */
  static private HttpURLConnection tryRequest(String apiCall) throws IOException {
    // Configure the connection (but don't actually send the request yet)
    URL requestURL = new URL("http://localhost:"+Spark.port()+"/"+apiCall);
    HttpURLConnection clientConnection = (HttpURLConnection) requestURL.openConnection();

    // The default method is "GET", which is what we're using here.
    // If we were using "POST", we'd need to say so.
    //clientConnection.setRequestMethod("GET");

    clientConnection.connect();
    return clientConnection;
  }

  /**
   * Helper function to read JSON from moshi. Used for testing
   *
   * @param clientConnection - the HTTP URL connection resulting from sending an API query
   * @return a map of String, Object pairs generated by moshi
   */
  static private Map<String, Object> getResponse(HttpURLConnection clientConnection) throws IOException {
    return moshi.adapter(Types.newParameterizedType(Map.class, String.class, Object.class))
        .fromJson(new Buffer().readFrom(clientConnection.getInputStream()));
  }

}
